services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT server.app:app  
    envVars:
      - key: DATABASE_URL
        value: your_database_url
