"""Added a artist name column

Revision ID: 561cdf6f6608
Revises: 01e2561ca550
Create Date: 2024-04-15 18:24:39.425285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561cdf6f6608'
down_revision = '01e2561ca550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
